# Site settings
title: Wuhuama's Blog
email: duan_wuhuama@163.com
description: Wuhuama's Ideas & Blogs
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: wuhuama
github_username: wuhuama
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/wuhuama.github.io/blob/master/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/wuhuama.github.io/new/master
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: wuhuama
#duoshuo_url: "http://wuhuama.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: wuhuama
disqus_url: "http://wuhuama.github.io"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
